name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: '13'
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build:prod
