---
name: CI

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - run: yarn install
      - run: yarn build:prod
